/*
 * generated by Xtext
 */
package net.immute.ccs.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CcsEclipseUiModule extends net.immute.ccs.ui.AbstractCcsEclipseUiModule {
	public CcsEclipseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
