/*
 * generated by Xtext
 */
package net.immute.ccs;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CcsEclipseRuntimeModule extends net.immute.ccs.AbstractCcsEclipseRuntimeModule {

}
