/*
 * generated by Xtext
 */
package net.immute.ccs.serializer;

import com.google.inject.Inject;
import java.util.List;
import net.immute.ccs.services.CcsEclipseGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class CcsEclipseSyntacticSequencer extends AbstractSyntacticSequencer {

	protected CcsEclipseGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Context_SemicolonKeyword_4_q;
	protected AbstractElementAlias match_Rule_SemicolonKeyword_1_q;
	protected AbstractElementAlias match_Selector_GreaterThanSignKeyword_1_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (CcsEclipseGrammarAccess) access;
		match_Context_SemicolonKeyword_4_q = new TokenAlias(false, true, grammarAccess.getContextAccess().getSemicolonKeyword_4());
		match_Rule_SemicolonKeyword_1_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getSemicolonKeyword_1());
		match_Selector_GreaterThanSignKeyword_1_q = new TokenAlias(false, true, grammarAccess.getSelectorAccess().getGreaterThanSignKeyword_1());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Context_SemicolonKeyword_4_q.equals(syntax))
				emit_Context_SemicolonKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rule_SemicolonKeyword_1_q.equals(syntax))
				emit_Rule_SemicolonKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Selector_GreaterThanSignKeyword_1_q.equals(syntax))
				emit_Selector_GreaterThanSignKeyword_1_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     selector=Selector ')' (ambiguity) (rule end)
	 */
	protected void emit_Context_SemicolonKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constraint=Constraint (ambiguity) (rule end)
	 *     import=Import (ambiguity) (rule end)
	 *     nested=Nested (ambiguity) (rule end)
	 *     property=Property (ambiguity) (rule end)
	 */
	protected void emit_Rule_SemicolonKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '>'?
	 *
	 * This ambiguous syntax occurs at:
	 *     sum=Sum (ambiguity) (rule end)
	 */
	protected void emit_Selector_GreaterThanSignKeyword_1_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
