/**
 * generated by Xtext
 */
package net.immute.ccs.validation;

import net.immute.ccs.validation.AbstractCcsEclipseValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class CcsEclipseValidator extends AbstractCcsEclipseValidator {
}
