/**
 * generated by Xtext
 */
package net.immute.ccs.ui.contentassist;

import net.immute.ccs.ui.contentassist.AbstractCcsEclipseProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CcsEclipseProposalProvider extends AbstractCcsEclipseProposalProvider {
}
