/*
* generated by Xtext
*/
package net.immute.ccs.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CcsEclipseAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("net/immute/ccs/parser/antlr/internal/InternalCcsEclipse.tokens");
	}
}
