/*
 * generated by Xtext
 */
package net.immute.ccs.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCcsEclipseValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(net.immute.ccs.ccsEclipse.CcsEclipsePackage.eINSTANCE);
		return result;
	}
}
